name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up
    - name: Verify with curl
      uses: wei/curl@v1.1.1
      with:
        args: http://localhost:5000/chat -H "Content-Type:application/json" -d '{"message":"I am crazy"}'
      
    


